version: "3"
services:
  mongorest:
    container_name: mongorest
    build: .
    image: fabiopasilva1/mongorest:version1.1.5
    restart: unless-stopped
    env_file: .env
    environment:
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB: ${MONGODB_DB}
      API_PORT: ${API_PORT}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./src/config:/opt/uneel/mongorest/app/src/config
      - ./src:/opt/uneel/mongorest/app/src
      - ./package.json:/opt/uneelmongorest/package.json
      - ./.env:/opt/uneel/mongorest/app/.env
      - ./swagger-output.json:/opt/uneel/mongorest/app/swagger-output.json
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - uneel
    mem_limit: 2024m
    cpus: "2"
volumes:
  uneel-data:

networks:
  uneel:
    name: StrapiUneel
    driver: bridge
